### ISSUE TITLE
vscodium editor apparently not supported

### ISSUE THREAD

**Issue by kirisakow** [yyx990803/launch-editor#12]
I can't see vscodium editor among the supported editors.  Is vscodium support under way at all?
Pair issue created: VSCodium/vscodium#140
(Thank you for what you do, no matter what)

**Comment by kirisakow** [comment]
Fork created and proposal submitted: 
https://github.com/yyx990803/launch-editor/commit/b9af8c1c41050dd5f23642149262715fee730e10

**Comment by kirisakow** [comment]
https://github.com/yyx990803/launch-editor/commit/253d3ebef9afb476d702fc2732e37d1535aea942

**Comment by yyx990803** [comment]
Please submit pull requests for the changes.

**Comment by kirisakow** [comment]
Have just done, see #13  and #14 . Sorry for the inconvenience.
