### ISSUE TITLE
Open component with IntelliJ 2017.3

### ISSUE THREAD

**Issue by sybrendotinga** [yyx990803/launch-editor#3]
I am getting an error with IntelliJ whilst opening a component trough the Vue Dev Tools. 

<img width="423" alt="schermafbeelding 2018-01-14 om 15 25 39" src="https://user-images.githubusercontent.com/14016492/34917055-a1b6e70a-f941-11e7-9cfb-c17b53af5abb.png">

I'm using a MacBook Pro with High Sierra 10.13.2 and the following setup:
Versions: 

```
webpack: 3.10.0
webpack-dev-server: 2.10.1
yarn: 1.3.2
node: 8.5.0
```
While having HMR enabled I get the following output in my terminal: 
```bash
webpack: Compiled successfully.
2018-01-14 15:43:32.577 idea[36772:3014555] allVms required 1.8*,1.8+
2018-01-14 15:43:32.580 idea[36772:3014563] Value of IDEA_VM_OPTIONS is (null)
2018-01-14 15:43:32.580 idea[36772:3014563] fullFileName is: /Applications/IntelliJ IDEA.app/Contents/bin/idea.vmoptions
2018-01-14 15:43:32.580 idea[36772:3014563] fullFileName exists: /Applications/IntelliJ IDEA.app/Contents/bin/idea.vmoptions
2018-01-14 15:43:32.581 idea[36772:3014563] Processing VMOptions file at /Applications/IntelliJ IDEA.app/Contents/bin/idea.vmoptions
2018-01-14 15:43:32.581 idea[36772:3014563] Done
Already running
```
This is my code to run the webpack-dev-server:

```js
  devServer: {
      contentBase: commonPaths.publicPath,
      hot: true,
      overlay: true,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
        'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization'
      },
      allowedHosts: [
        'localhost'
      ],
      before(app){
        app.use('/__open-in-editor', openInEditor())
      }
    },
```
If you need more information, just let me know and I will try to provide you with it.

**Comment by yyx990803** [comment]
Looks like devtools got a relative path in the codebase... let's move this to the devtools repo instead.

**Comment by yyx990803** [comment]
Nevermind, it's because Idea can't open relative paths. I think we need to add an option for the middleware to specify where the src root is.

**Comment by yyx990803** [comment]
Middleware 2.2.0 now always passes absolute paths to editors. Try upgrading.

**Comment by sybrendotinga** [comment]
Thanks a bunch! That fixed the issue.
