### ISSUE TITLE
MacOS Webstorm

### ISSUE THREAD

**Issue by Akryum** [yyx990803/launch-editor#4]
```js
// not works
openInEditor('webstorm')

// works!
openInEditor('/Applications/WebStorm.app/Contents/MacOS/webstorm')
```

Source: https://medium.com/@jungjoo/great-d0a745a560a8

**Comment by moreta** [comment]
If Command Line Launcher Installed

```
// this works!
openInEditor('webstorm')
```

## install jetbrain editors command line

`"Tools" -> "Create Command Line Launcher..."`

![jetbrain's editor cli install](https://user-images.githubusercontent.com/115768/35209734-bc2127de-ff92-11e7-8e2f-f003f0500536.png)

**Comment by yyx990803** [comment]
Yeah if using binary shorthand, the binary needs to be in PATH. I think this is expected behavior...
