### ISSUE TITLE
MacOS VS Code

### ISSUE THREAD

**Issue by Akryum** [yyx990803/launch-editor#5]
```js
const openInEditor = require('launch-editor', 'code')
openInEditor('./shells/dev/target/Target.vue')
```

<img width="441" alt="capture d ecran 2018-01-19 a 11 10 28" src="https://user-images.githubusercontent.com/2798204/35145796-63f5041c-fd09-11e7-9d75-b9acf8fb5e49.png">

**Comment by moreta** [comment]
First, Install Command Line Launcher

![vs shell-command install](https://code.visualstudio.com/assets/docs/setup/mac/shell-command.png)

**Comment by yyx990803** [comment]
Same w/ #4. I guess we can update the docs to indicate that.

**Comment by Akryum** [comment]
I don't remember to have to do anything on Linux for this to work. :smile:
