### ISSUE TITLE
Supported editors - Ubuntu - Sublime is not working 

### ISSUE THREAD

**Issue by kk-r** [yyx990803/launch-editor#6]
I'm getting this error - `Could not open Sidebar.vue in the editor.
The editor process exited with an error: spawn sublime ENOENT.`.

If I used keyword - ` subl ` - as value that's working fine.

**Comment by yyx990803** [comment]
Did you link the bin yourself? I know it's convention to name it `subl` but AFAIK Sublime on Linux doesn't use that binary name by default.

**Comment by kk-r** [comment]
I did't link bin manually. I checked on ubuntu sublime both 2/3 have binary name as `subl`.

**Comment by yyx990803** [comment]
I see, what we need to do is updating [this line](https://github.com/yyx990803/launch-editor/blob/master/packages/launch-editor/editor-info/linux.js#L10). Can you try locally changing it to `subl` and see if that works?

what is Sublime's process name when you do `ps x --no-heading -o comm --sort=comm`?

**Comment by kk-r** [comment]
In local I changed to `subl` it's working. :smile: 

And I checked Sublime's process name is **sublime_text**.

**Comment by kk-r** [comment]
@yyx990803 Thanks.
