### ISSUE TITLE
Can you add support rider ?

### ISSUE THREAD

**Issue by alexisdevise** [yyx990803/launch-editor#62]
i did't see in supported editors rider

**Comment by Exponential-Workload** [comment]
https://github.com/yyx990803/launch-editor/blob/5ad87f680410710e261f4acdaddecaa808312029/packages/launch-editor/editor-info/windows.js#L23-L24

https://github.com/yyx990803/launch-editor/blob/5ad87f680410710e261f4acdaddecaa808312029/packages/launch-editor/editor-info/linux.js#L18
