### ISSUE TITLE
Missing comma in packages/launch-editor/editor-info/linux.js

### ISSUE THREAD

**Issue by RaZeR2604** [yyx990803/launch-editor#79]
There is an error in packages/launch-editor/editor-info/linux.js

module.exports = {
  atom: 'atom',
  Brackets: 'brackets',
  'code-insiders': 'code-insiders',
  code: 'code',
  vscodium: 'vscodium',
  codium: 'codium',
  emacs: 'emacs',
  gvim: 'gvim',
  idea: 'idea',
  'idea.sh': 'idea',
  phpstorm: 'phpstorm',
  'phpstorm.sh': 'phpstorm',
  pycharm: 'pycharm',
  'pycharm.sh': 'pycharm',
  rubymine: 'rubymine',
  'rubymine.sh': 'rubymine',
  sublime_text: 'subl',
  vim: 'vim',
  webstorm: 'webstorm',
  'webstorm.sh': 'webstorm',
  goland: 'goland',
  'goland.sh': 'goland',
  rider: 'rider', <--
  'rider.sh': 'rider'
}

**Comment by AuspeXeu** [comment]
https://github.com/yyx990803/launch-editor/pull/80

**Comment by haoqunjiang** [comment]
Thanks 🙏
Fixed in 2.9.1
